<?php
namespace SpeedPress\Addons;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class Catalog {
	public static function groups() {
		return array(
			'content' => 'Content',
			'media' => 'Media',
			'marketing' => 'Marketing',
			'proof' => 'Social proof',
			'data' => 'Data',
			'theme' => 'Theme / blog',
			'business' => 'Business',
			'forms' => 'Forms / embed',
			'woo' => 'WooCommerce',
			'utility' => 'Utility',
		);
	}

	public static function all() {
		return array(
			'dual-heading' => array(
				'title'       => 'Dual Heading',
				'description' => 'Two-color heading pair.',
				'group'       => 'content',
				'icon'        => 'eicon-heading',
				'type'        => 'dual_heading',
			),
			'gradient-heading' => array(
				'title'       => 'Gradient Heading',
				'description' => 'Heading with a two-stop gradient.',
				'group'       => 'content',
				'icon'        => 'eicon-heading',
				'type'        => 'gradient_heading',
			),
			'typed-heading' => array(
				'title'       => 'Typed Heading',
				'description' => 'Rotating words after a static prefix.',
				'group'       => 'content',
				'icon'        => 'eicon-animation-text',
				'type'        => 'typed_heading',
			),
			'highlight-heading' => array(
				'title'       => 'Highlight Heading',
				'description' => 'Heading with a marked phrase.',
				'group'       => 'content',
				'icon'        => 'eicon-heading',
				'type'        => 'highlight_heading',
			),
			'drop-cap-text' => array(
				'title'       => 'Drop Cap Text',
				'description' => 'Opening paragraph with a large first letter.',
				'group'       => 'content',
				'icon'        => 'eicon-text',
				'type'        => 'drop_cap',
			),
			'pull-quote' => array(
				'title'       => 'Pull Quote',
				'description' => 'Large quote with optional cite.',
				'group'       => 'content',
				'icon'        => 'eicon-editor-quote',
				'type'        => 'quote',
			),
			'info-box' => array(
				'title'       => 'Info Box',
				'description' => 'Icon, title, and supporting text.',
				'group'       => 'content',
				'icon'        => 'eicon-info-box',
				'type'        => 'icon_box',
			),
			'icon-box' => array(
				'title'       => 'Icon Box',
				'description' => 'Simple icon + label block.',
				'group'       => 'content',
				'icon'        => 'eicon-icon-box',
				'type'        => 'icon_box',
			),
			'image-box' => array(
				'title'       => 'Image Box',
				'description' => 'Image, title, and text card.',
				'group'       => 'content',
				'icon'        => 'eicon-image-box',
				'type'        => 'image_box',
			),
			'hover-card' => array(
				'title'       => 'Hover Card',
				'description' => 'Card that lifts and reveals a button.',
				'group'       => 'content',
				'icon'        => 'eicon-info-box',
				'type'        => 'hover_card',
			),
			'flip-card' => array(
				'title'       => 'Flip Card',
				'description' => 'Two-sided card on hover.',
				'group'       => 'content',
				'icon'        => 'eicon-flip-box',
				'type'        => 'flip_card',
			),
			'overlay-card' => array(
				'title'       => 'Overlay Card',
				'description' => 'Image with text overlay.',
				'group'       => 'content',
				'icon'        => 'eicon-image-rollover',
				'type'        => 'overlay_card',
			),
			'feature-list' => array(
				'title'       => 'Feature List',
				'description' => 'Title + short text rows.',
				'group'       => 'content',
				'icon'        => 'eicon-bullet-list',
				'type'        => 'feature_list',
			),
			'check-list' => array(
				'title'       => 'Check List',
				'description' => 'Checklist with custom marks.',
				'group'       => 'content',
				'icon'        => 'eicon-check-circle',
				'type'        => 'check_list',
			),
			'numbered-list' => array(
				'title'       => 'Numbered List',
				'description' => 'Steps shown as numbered rows.',
				'group'       => 'content',
				'icon'        => 'eicon-number-field',
				'type'        => 'numbered_list',
			),
			'icon-list' => array(
				'title'       => 'Icon List',
				'description' => 'Rows with a leading mark and text.',
				'group'       => 'content',
				'icon'        => 'eicon-bullet-list',
				'type'        => 'icon_list',
			),
			'steps-process' => array(
				'title'       => 'Steps Process',
				'description' => 'Horizontal or stacked process steps.',
				'group'       => 'content',
				'icon'        => 'eicon-flow',
				'type'        => 'steps',
			),
			'timeline' => array(
				'title'       => 'Timeline',
				'description' => 'Vertical event timeline.',
				'group'       => 'content',
				'icon'        => 'eicon-time-line',
				'type'        => 'timeline',
			),
			'horizontal-timeline' => array(
				'title'       => 'Horizontal Timeline',
				'description' => 'Events in a row with dates.',
				'group'       => 'content',
				'icon'        => 'eicon-time-line',
				'type'        => 'h_timeline',
			),
			'content-tabs' => array(
				'title'       => 'Content Tabs',
				'description' => 'Tabbed panels.',
				'group'       => 'content',
				'icon'        => 'eicon-tabs',
				'type'        => 'tabs',
			),
			'vertical-tabs' => array(
				'title'       => 'Vertical Tabs',
				'description' => 'Tabs stacked on the side.',
				'group'       => 'content',
				'icon'        => 'eicon-tabs',
				'type'        => 'tabs_vertical',
			),
			'toggle-list' => array(
				'title'       => 'Toggle List',
				'description' => 'One-open accordion list.',
				'group'       => 'content',
				'icon'        => 'eicon-toggle',
				'type'        => 'toggles',
			),
			'tooltip-note' => array(
				'title'       => 'Tooltip Note',
				'description' => 'Inline note with extra detail.',
				'group'       => 'content',
				'icon'        => 'eicon-info-circle-o',
				'type'        => 'tooltip',
			),
			'alert-box' => array(
				'title'       => 'Alert Box',
				'description' => 'Success, warning, or info notice.',
				'group'       => 'content',
				'icon'        => 'eicon-alert',
				'type'        => 'alert',
			),
			'notice-bar' => array(
				'title'       => 'Notice Bar',
				'description' => 'Full-width site notice.',
				'group'       => 'content',
				'icon'        => 'eicon-banner',
				'type'        => 'notice',
			),
			'badge-pill' => array(
				'title'       => 'Badge Pill',
				'description' => 'Small status pill.',
				'group'       => 'content',
				'icon'        => 'eicon-site-identity',
				'type'        => 'badge',
			),
			'ribbon' => array(
				'title'       => 'Corner Ribbon',
				'description' => 'Corner label over content.',
				'group'       => 'content',
				'icon'        => 'eicon-banner',
				'type'        => 'ribbon',
			),
			'divider-label' => array(
				'title'       => 'Labeled Divider',
				'description' => 'Line with centered label.',
				'group'       => 'content',
				'icon'        => 'eicon-divider',
				'type'        => 'divider_label',
			),
			'shape-separator' => array(
				'title'       => 'Shape Separator',
				'description' => 'Decorative section break.',
				'group'       => 'content',
				'icon'        => 'eicon-divider',
				'type'        => 'shape_sep',
			),
			'animated-link' => array(
				'title'       => 'Animated Link',
				'description' => 'Text link with underline motion.',
				'group'       => 'content',
				'icon'        => 'eicon-editor-link',
				'type'        => 'anim_link',
			),
			'image-caption' => array(
				'title'       => 'Image Caption',
				'description' => 'Image with a caption bar.',
				'group'       => 'media',
				'icon'        => 'eicon-image',
				'type'        => 'image_caption',
			),
			'image-overlay' => array(
				'title'       => 'Image Overlay',
				'description' => 'Image with hover title.',
				'group'       => 'media',
				'icon'        => 'eicon-image-rollover',
				'type'        => 'image_overlay',
			),
			'image-grid' => array(
				'title'       => 'Image Grid',
				'description' => 'Simple responsive image grid.',
				'group'       => 'media',
				'icon'        => 'eicon-gallery-grid',
				'type'        => 'image_grid',
			),
			'logo-grid' => array(
				'title'       => 'Logo Grid',
				'description' => 'Partner / client logo grid.',
				'group'       => 'media',
				'icon'        => 'eicon-logo',
				'type'        => 'logo_grid',
			),
			'logo-slider' => array(
				'title'       => 'Logo Slider',
				'description' => 'Scrolling logo row.',
				'group'       => 'media',
				'icon'        => 'eicon-carousel',
				'type'        => 'logo_slider',
			),
			'video-embed' => array(
				'title'       => 'Video Embed',
				'description' => 'YouTube or Vimeo URL embed.',
				'group'       => 'media',
				'icon'        => 'eicon-youtube',
				'type'        => 'video',
			),
			'video-popup' => array(
				'title'       => 'Video Popup',
				'description' => 'Thumbnail that opens a video link.',
				'group'       => 'media',
				'icon'        => 'eicon-video-camera',
				'type'        => 'video_popup',
			),
			'before-after' => array(
				'title'       => 'Before After',
				'description' => 'Two-image comparison slider.',
				'group'       => 'media',
				'icon'        => 'eicon-image-before-after',
				'type'        => 'before_after',
			),
			'image-hotspots' => array(
				'title'       => 'Image Hotspots',
				'description' => 'Clickable notes on an image.',
				'group'       => 'media',
				'icon'        => 'eicon-image-hotspot',
				'type'        => 'hotspots',
			),
			'photo-stack' => array(
				'title'       => 'Photo Stack',
				'description' => 'Layered photo group.',
				'group'       => 'media',
				'icon'        => 'eicon-photo-library',
				'type'        => 'photo_stack',
			),
			'polaroid' => array(
				'title'       => 'Polaroid',
				'description' => 'Framed photo with handwriting caption.',
				'group'       => 'media',
				'icon'        => 'eicon-image-box',
				'type'        => 'polaroid',
			),
			'device-frame' => array(
				'title'       => 'Device Frame',
				'description' => 'Image inside a simple device bezel.',
				'group'       => 'media',
				'icon'        => 'eicon-device-desktop',
				'type'        => 'device',
			),
			'lightbox-gallery' => array(
				'title'       => 'Lightbox Gallery',
				'description' => 'Gallery that opens full images.',
				'group'       => 'media',
				'icon'        => 'eicon-lightbox-expand',
				'type'        => 'gallery',
			),
			'image-accordion' => array(
				'title'       => 'Image Accordion',
				'description' => 'Expanding image panels.',
				'group'       => 'media',
				'icon'        => 'eicon-accordion',
				'type'        => 'image_acc',
			),
			'dual-button' => array(
				'title'       => 'Dual Button',
				'description' => 'Primary and secondary actions.',
				'group'       => 'marketing',
				'icon'        => 'eicon-dual-button',
				'type'        => 'dual_button',
			),
			'creative-button' => array(
				'title'       => 'Creative Button',
				'description' => 'Button with hover fill.',
				'group'       => 'marketing',
				'icon'        => 'eicon-button',
				'type'        => 'creative_button',
			),
			'download-button' => array(
				'title'       => 'Download Button',
				'description' => 'File or URL download CTA.',
				'group'       => 'marketing',
				'icon'        => 'eicon-download-button',
				'type'        => 'download_btn',
			),
			'call-button' => array(
				'title'       => 'Call Button',
				'description' => 'Click-to-call phone button.',
				'group'       => 'marketing',
				'icon'        => 'eicon-tel-field',
				'type'        => 'call_btn',
			),
			'promo-banner' => array(
				'title'       => 'Promo Banner',
				'description' => 'Wide offer banner.',
				'group'       => 'marketing',
				'icon'        => 'eicon-banner',
				'type'        => 'promo',
			),
			'offer-card' => array(
				'title'       => 'Offer Card',
				'description' => 'Discount card with expiry note.',
				'group'       => 'marketing',
				'icon'        => 'eicon-price-table',
				'type'        => 'offer',
			),
			'coupon-code' => array(
				'title'       => 'Coupon Code',
				'description' => 'Copyable coupon string.',
				'group'       => 'marketing',
				'icon'        => 'eicon-barcode',
				'type'        => 'coupon',
			),
			'countdown' => array(
				'title'       => 'Countdown',
				'description' => 'Target date countdown.',
				'group'       => 'marketing',
				'icon'        => 'eicon-countdown',
				'type'        => 'countdown',
			),
			'launch-banner' => array(
				'title'       => 'Launch Banner',
				'description' => 'Launch date plus countdown.',
				'group'       => 'marketing',
				'icon'        => 'eicon-countdown',
				'type'        => 'launch',
			),
			'price-list' => array(
				'title'       => 'Price List',
				'description' => 'Menu-style name and price rows.',
				'group'       => 'marketing',
				'icon'        => 'eicon-price-list',
				'type'        => 'price_list',
			),
			'comparison-table' => array(
				'title'       => 'Comparison Table',
				'description' => 'Two-plan feature compare.',
				'group'       => 'marketing',
				'icon'        => 'eicon-table',
				'type'        => 'compare',
			),
			'pricing-switch' => array(
				'title'       => 'Pricing Switch',
				'description' => 'Monthly / yearly pair of plans.',
				'group'       => 'marketing',
				'icon'        => 'eicon-price-table',
				'type'        => 'price_switch',
			),
			'cta-split' => array(
				'title'       => 'Split CTA',
				'description' => 'Text on one side, button on the other.',
				'group'       => 'marketing',
				'icon'        => 'eicon-call-to-action',
				'type'        => 'cta_split',
			),
			'newsletter-box' => array(
				'title'       => 'Newsletter Box',
				'description' => 'Email field markup or shortcode.',
				'group'       => 'marketing',
				'icon'        => 'eicon-mail',
				'type'        => 'newsletter',
			),
			'lead-magnet' => array(
				'title'       => 'Lead Magnet',
				'description' => 'Download offer with form shortcode.',
				'group'       => 'marketing',
				'icon'        => 'eicon-download-kit',
				'type'        => 'lead',
			),
			'modal-cta' => array(
				'title'       => 'Modal CTA',
				'description' => 'Button that opens a content panel.',
				'group'       => 'marketing',
				'icon'        => 'eicon-button',
				'type'        => 'modal',
			),
			'review-card' => array(
				'title'       => 'Review Card',
				'description' => 'Star review with author.',
				'group'       => 'proof',
				'icon'        => 'eicon-review',
				'type'        => 'review',
			),
			'rating-badge' => array(
				'title'       => 'Rating Badge',
				'description' => 'Aggregate score badge.',
				'group'       => 'proof',
				'icon'        => 'eicon-review',
				'type'        => 'rating_badge',
			),
			'testimonial-slider' => array(
				'title'       => 'Testimonial Slider',
				'description' => 'Rotating quotes.',
				'group'       => 'proof',
				'icon'        => 'eicon-testimonial-carousel',
				'type'        => 't_slider',
			),
			'team-member' => array(
				'title'       => 'Team Member',
				'description' => 'Photo, name, role, bio.',
				'group'       => 'proof',
				'icon'        => 'eicon-person',
				'type'        => 'team',
			),
			'team-grid' => array(
				'title'       => 'Team Grid',
				'description' => 'Repeater of team cards.',
				'group'       => 'proof',
				'icon'        => 'eicon-person',
				'type'        => 'team_grid',
			),
			'client-logos' => array(
				'title'       => 'Client Logos',
				'description' => 'Trusted-by logo row.',
				'group'       => 'proof',
				'icon'        => 'eicon-logo',
				'type'        => 'logo_grid',
			),
			'case-study-card' => array(
				'title'       => 'Case Study Card',
				'description' => 'Result highlight with metric.',
				'group'       => 'proof',
				'icon'        => 'eicon-archive-posts',
				'type'        => 'case_study',
			),
			'star-rating' => array(
				'title'       => 'Star Rating',
				'description' => 'Visual star score.',
				'group'       => 'proof',
				'icon'        => 'eicon-review',
				'type'        => 'stars',
			),
			'logo-cloud' => array(
				'title'       => 'Logo Cloud',
				'description' => 'Wrapped logo collection.',
				'group'       => 'proof',
				'icon'        => 'eicon-gallery-justified',
				'type'        => 'logo_cloud',
			),
			'progress-bar' => array(
				'title'       => 'Progress Bar',
				'description' => 'Single labeled bar.',
				'group'       => 'data',
				'icon'        => 'eicon-skill-bar',
				'type'        => 'progress',
			),
			'skill-bars' => array(
				'title'       => 'Skill Bars',
				'description' => 'Multiple labeled bars.',
				'group'       => 'data',
				'icon'        => 'eicon-skill-bar',
				'type'        => 'skills',
			),
			'circle-progress' => array(
				'title'       => 'Circle Progress',
				'description' => 'SVG ring percent.',
				'group'       => 'data',
				'icon'        => 'eicon-counter-circle',
				'type'        => 'circle',
			),
			'big-counter' => array(
				'title'       => 'Big Counter',
				'description' => 'One large animated number.',
				'group'       => 'data',
				'icon'        => 'eicon-counter',
				'type'        => 'big_counter',
			),
			'stat-card' => array(
				'title'       => 'Stat Card',
				'description' => 'Number with label and note.',
				'group'       => 'data',
				'icon'        => 'eicon-counter',
				'type'        => 'stat_card',
			),
			'pie-stat' => array(
				'title'       => 'Pie Stat',
				'description' => 'CSS conic percent.',
				'group'       => 'data',
				'icon'        => 'eicon-banner',
				'type'        => 'pie',
			),
			'simple-bars' => array(
				'title'       => 'Simple Bars',
				'description' => 'CSS bar chart from values.',
				'group'       => 'data',
				'icon'        => 'eicon-skill-bar',
				'type'        => 'bars',
			),
			'data-table' => array(
				'title'       => 'Data Table',
				'description' => 'Simple rows and columns.',
				'group'       => 'data',
				'icon'        => 'eicon-table',
				'type'        => 'table',
			),
			'specs-table' => array(
				'title'       => 'Specs Table',
				'description' => 'Label / value specification list.',
				'group'       => 'data',
				'icon'        => 'eicon-table',
				'type'        => 'specs',
			),
			'site-logo' => array(
				'title'       => 'Site Logo',
				'description' => 'Custom logo or customizer logo.',
				'group'       => 'theme',
				'icon'        => 'eicon-logo',
				'type'        => 'site_logo',
			),
			'site-title' => array(
				'title'       => 'Site Title',
				'description' => 'Blog name from WordPress.',
				'group'       => 'theme',
				'icon'        => 'eicon-site-title',
				'type'        => 'site_title',
			),
			'site-tagline' => array(
				'title'       => 'Site Tagline',
				'description' => 'Tagline from WordPress.',
				'group'       => 'theme',
				'icon'        => 'eicon-site-identity',
				'type'        => 'site_tagline',
			),
			'page-title' => array(
				'title'       => 'Page Title',
				'description' => 'Current page or post title.',
				'group'       => 'theme',
				'icon'        => 'eicon-post-title',
				'type'        => 'page_title',
			),
			'breadcrumbs' => array(
				'title'       => 'Breadcrumbs',
				'description' => 'Home / parent / current trail.',
				'group'       => 'theme',
				'icon'        => 'eicon-chevron-right',
				'type'        => 'breadcrumbs',
			),
			'nav-menu' => array(
				'title'       => 'Nav Menu',
				'description' => 'Any registered WP menu.',
				'group'       => 'theme',
				'icon'        => 'eicon-nav-menu',
				'type'        => 'menu',
			),
			'search-form' => array(
				'title'       => 'Search Form',
				'description' => 'WordPress search field.',
				'group'       => 'theme',
				'icon'        => 'eicon-search',
				'type'        => 'search',
			),
			'author-box' => array(
				'title'       => 'Author Box',
				'description' => 'Post author bio box.',
				'group'       => 'theme',
				'icon'        => 'eicon-person',
				'type'        => 'author',
			),
			'post-meta' => array(
				'title'       => 'Post Meta',
				'description' => 'Date, author, and categories.',
				'group'       => 'theme',
				'icon'        => 'eicon-post-info',
				'type'        => 'post_meta',
			),
			'post-grid' => array(
				'title'       => 'Post Grid',
				'description' => 'Latest posts in a grid.',
				'group'       => 'theme',
				'icon'        => 'eicon-posts-grid',
				'type'        => 'posts_grid',
			),
			'post-list' => array(
				'title'       => 'Post List',
				'description' => 'Compact latest posts.',
				'group'       => 'theme',
				'icon'        => 'eicon-post-list',
				'type'        => 'posts_list',
			),
			'post-tiles' => array(
				'title'       => 'Post Tiles',
				'description' => 'Featured image tiles.',
				'group'       => 'theme',
				'icon'        => 'eicon-gallery-justified',
				'type'        => 'posts_tiles',
			),
			'category-cards' => array(
				'title'       => 'Category Cards',
				'description' => 'Post category cards.',
				'group'       => 'theme',
				'icon'        => 'eicon-sitemap',
				'type'        => 'cats',
			),
			'archive-header' => array(
				'title'       => 'Archive Header',
				'description' => 'Archive or blog heading.',
				'group'       => 'theme',
				'icon'        => 'eicon-archive-title',
				'type'        => 'archive_head',
			),
			'reading-time' => array(
				'title'       => 'Reading Time',
				'description' => 'Estimated minutes for the post.',
				'group'       => 'theme',
				'icon'        => 'eicon-time-line',
				'type'        => 'read_time',
			),
			'table-of-contents' => array(
				'title'       => 'Table of Contents',
				'description' => 'Links built from the post content headings.',
				'group'       => 'theme',
				'icon'        => 'eicon-table-of-contents',
				'type'        => 'toc',
			),
			'business-hours' => array(
				'title'       => 'Business Hours',
				'description' => 'Weekday opening hours.',
				'group'       => 'business',
				'icon'        => 'eicon-clock-o',
				'type'        => 'hours',
			),
			'contact-card' => array(
				'title'       => 'Contact Card',
				'description' => 'Name, phone, email, address.',
				'group'       => 'business',
				'icon'        => 'eicon-tel-field',
				'type'        => 'contact',
			),
			'address-block' => array(
				'title'       => 'Address Block',
				'description' => 'NAP block for local pages.',
				'group'       => 'business',
				'icon'        => 'eicon-google-maps',
				'type'        => 'address',
			),
			'google-map' => array(
				'title'       => 'Map Embed',
				'description' => 'Google Maps search embed.',
				'group'       => 'business',
				'icon'        => 'eicon-google-maps',
				'type'        => 'map',
			),
			'phone-bar' => array(
				'title'       => 'Phone Bar',
				'description' => 'Sticky-style call strip.',
				'group'       => 'business',
				'icon'        => 'eicon-tel-field',
				'type'        => 'phone_bar',
			),
			'whatsapp-button' => array(
				'title'       => 'WhatsApp Button',
				'description' => 'wa.me chat button.',
				'group'       => 'business',
				'icon'        => 'eicon-tel-field',
				'type'        => 'whatsapp',
			),
			'opening-status' => array(
				'title'       => 'Opening Status',
				'description' => 'Open or closed label.',
				'group'       => 'business',
				'icon'        => 'eicon-clock-o',
				'type'        => 'open_status',
			),
			'service-area' => array(
				'title'       => 'Service Area',
				'description' => 'Cities or regions you cover.',
				'group'       => 'business',
				'icon'        => 'eicon-map-pin',
				'type'        => 'service_area',
			),
			'appointment-cta' => array(
				'title'       => 'Appointment CTA',
				'description' => 'Book-a-time block.',
				'group'       => 'business',
				'icon'        => 'eicon-calendar',
				'type'        => 'appt',
			),
			'contact-form-7' => array(
				'title'       => 'Contact Form 7',
				'description' => 'Pick a CF7 form if installed.',
				'group'       => 'forms',
				'icon'        => 'eicon-form-horizontal',
				'type'        => 'cf7',
			),
			'wpforms-embed' => array(
				'title'       => 'WPForms Embed',
				'description' => 'Pick a WPForms form if installed.',
				'group'       => 'forms',
				'icon'        => 'eicon-form-horizontal',
				'type'        => 'wpforms',
			),
			'shortcode-box' => array(
				'title'       => 'Shortcode Box',
				'description' => 'Render any shortcode.',
				'group'       => 'forms',
				'icon'        => 'eicon-shortcode',
				'type'        => 'shortcode',
			),
			'login-form' => array(
				'title'       => 'Login Form',
				'description' => 'WordPress login form.',
				'group'       => 'forms',
				'icon'        => 'eicon-lock-user',
				'type'        => 'login',
			),
			'mailchimp-embed' => array(
				'title'       => 'Mailchimp Embed',
				'description' => 'Paste embed HTML or shortcode.',
				'group'       => 'forms',
				'icon'        => 'eicon-mail',
				'type'        => 'html_embed',
			),
			'html-embed' => array(
				'title'       => 'HTML Embed',
				'description' => 'Trusted embed markup.',
				'group'       => 'forms',
				'icon'        => 'eicon-code',
				'type'        => 'html_embed',
			),
			'source-code' => array(
				'title'       => 'Source Code',
				'description' => 'Escaped code sample.',
				'group'       => 'forms',
				'icon'        => 'eicon-code',
				'type'        => 'code',
			),
			'pdf-link' => array(
				'title'       => 'PDF Link',
				'description' => 'Button linking to a PDF.',
				'group'       => 'forms',
				'icon'        => 'eicon-document-file',
				'type'        => 'pdf',
			),
			'woo-products' => array(
				'title'       => 'Woo Products',
				'description' => 'Latest products if WooCommerce is active.',
				'group'       => 'woo',
				'icon'        => 'eicon-products',
				'type'        => 'woo_products',
			),
			'woo-categories' => array(
				'title'       => 'Woo Categories',
				'description' => 'Product category cards.',
				'group'       => 'woo',
				'icon'        => 'eicon-product-categories',
				'type'        => 'woo_cats',
			),
			'woo-add-to-cart' => array(
				'title'       => 'Woo Add to Cart',
				'description' => 'Add-to-cart for one product ID.',
				'group'       => 'woo',
				'icon'        => 'eicon-product-add-to-cart',
				'type'        => 'woo_atc',
			),
			'woo-sale-badge' => array(
				'title'       => 'Woo Sale Badge',
				'description' => 'On-sale count or badge.',
				'group'       => 'woo',
				'icon'        => 'eicon-sale-badge',
				'type'        => 'woo_sale',
			),
			'news-ticker' => array(
				'title'       => 'News Ticker',
				'description' => 'Scrolling headlines.',
				'group'       => 'utility',
				'icon'        => 'eicon-post-list',
				'type'        => 'ticker',
			),
			'marquee-text' => array(
				'title'       => 'Marquee Text',
				'description' => 'Endless scrolling sentence.',
				'group'       => 'utility',
				'icon'        => 'eicon-animation-text',
				'type'        => 'marquee',
			),
			'world-clock' => array(
				'title'       => 'World Clock',
				'description' => 'Local time for a timezone.',
				'group'       => 'utility',
				'icon'        => 'eicon-clock-o',
				'type'        => 'clock',
			),
			'weather-note' => array(
				'title'       => 'Weather Note',
				'description' => 'Manual weather line (no API key).',
				'group'       => 'utility',
				'icon'        => 'eicon-cloud-check',
				'type'        => 'weather',
			),
			'back-to-top' => array(
				'title'       => 'Back to Top',
				'description' => 'Jump-to-top control.',
				'group'       => 'utility',
				'icon'        => 'eicon-arrow-up',
				'type'        => 'top',
			),
			'cookie-note' => array(
				'title'       => 'Cookie Note',
				'description' => 'Simple consent bar markup.',
				'group'       => 'utility',
				'icon'        => 'eicon-banner',
				'type'        => 'cookie',
			),
			'age-notice' => array(
				'title'       => 'Age Notice',
				'description' => 'Age confirmation panel.',
				'group'       => 'utility',
				'icon'        => 'eicon-lock-user',
				'type'        => 'age',
			),
			'offcanvas-note' => array(
				'title'       => 'Off-canvas Note',
				'description' => 'Slide-in panel from a button.',
				'group'       => 'utility',
				'icon'        => 'eicon-menu-bar',
				'type'        => 'offcanvas',
			),
			'faq-schema-list' => array(
				'title'       => 'FAQ Schema List',
				'description' => 'FAQ items with FAQPage JSON-LD.',
				'group'       => 'utility',
				'icon'        => 'eicon-accordion',
				'type'        => 'faq_schema',
			),
			'protected-note' => array(
				'title'       => 'Protected Note',
				'description' => 'Content shown only to logged-in users.',
				'group'       => 'utility',
				'icon'        => 'eicon-lock-user',
				'type'        => 'protected',
			),
			'language-note' => array(
				'title'       => 'Language Note',
				'description' => 'Manual language / locale label.',
				'group'       => 'utility',
				'icon'        => 'eicon-site-identity',
				'type'        => 'lang',
			),
			'social-icons' => array(
				'title'       => 'Social Icons',
				'description' => 'Link row for profiles.',
				'group'       => 'utility',
				'icon'        => 'eicon-social-icons',
				'type'        => 'social',
			),
			'share-buttons' => array(
				'title'       => 'Share Buttons',
				'description' => 'Native share links for the current URL.',
				'group'       => 'utility',
				'icon'        => 'eicon-share',
				'type'        => 'share',
			),
			'author-list' => array(
				'title'       => 'Author List',
				'description' => 'Site authors.',
				'group'       => 'utility',
				'icon'        => 'eicon-person',
				'type'        => 'authors',
			),
			'tag-cloud' => array(
				'title'       => 'Tag Cloud',
				'description' => 'Post tag cloud.',
				'group'       => 'utility',
				'icon'        => 'eicon-tags',
				'type'        => 'tags',
			),
			'sitemap-list' => array(
				'title'       => 'Sitemap List',
				'description' => 'Page list grouped loosely.',
				'group'       => 'utility',
				'icon'        => 'eicon-sitemap',
				'type'        => 'sitemap',
			),
			'ical-note' => array(
				'title'       => 'Event Date',
				'description' => 'Single event date card.',
				'group'       => 'utility',
				'icon'        => 'eicon-calendar',
				'type'        => 'event',
			),
			'audio-link' => array(
				'title'       => 'Audio Link',
				'description' => 'Linked audio file player.',
				'group'       => 'utility',
				'icon'        => 'eicon-headphones',
				'type'        => 'audio',
			),
			'lottie-placeholder' => array(
				'title'       => 'Motion Box',
				'description' => 'CSS motion frame for a short loop.',
				'group'       => 'utility',
				'icon'        => 'eicon-animation',
				'type'        => 'motion',
			),
			'faq-lite' => array(
				'title'       => 'FAQ Lite',
				'description' => 'Short question list.',
				'group'       => 'content',
				'icon'        => 'eicon-accordion',
				'type'        => 'toggles',
			),
			'quote-band' => array(
				'title'       => 'Quote Band',
				'description' => 'Wide quote strip.',
				'group'       => 'content',
				'icon'        => 'eicon-editor-quote',
				'type'        => 'quote',
			),
			'kicker-heading' => array(
				'title'       => 'Kicker Heading',
				'description' => 'Small label over a title.',
				'group'       => 'content',
				'icon'        => 'eicon-heading',
				'type'        => 'dual_heading',
			),
			'section-intro' => array(
				'title'       => 'Section Intro',
				'description' => 'Title plus supporting paragraph.',
				'group'       => 'content',
				'icon'        => 'eicon-text',
				'type'        => 'generic',
			),
			'callout' => array(
				'title'       => 'Callout',
				'description' => 'Highlighted side note.',
				'group'       => 'content',
				'icon'        => 'eicon-info-box',
				'type'        => 'alert',
			),
			'definition-list' => array(
				'title'       => 'Definition List',
				'description' => 'Term and meaning rows.',
				'group'       => 'content',
				'icon'        => 'eicon-bullet-list',
				'type'        => 'specs',
			),
			'pros-list' => array(
				'title'       => 'Pros List',
				'description' => 'Positive points.',
				'group'       => 'content',
				'icon'        => 'eicon-check-circle',
				'type'        => 'check_list',
			),
			'cons-list' => array(
				'title'       => 'Cons List',
				'description' => 'Tradeoff points.',
				'group'       => 'content',
				'icon'        => 'eicon-close',
				'type'        => 'check_list',
			),
			'chip-list' => array(
				'title'       => 'Chip List',
				'description' => 'Inline tag chips.',
				'group'       => 'content',
				'icon'        => 'eicon-tags',
				'type'        => 'badge',
			),
			'two-column-text' => array(
				'title'       => 'Two Column Text',
				'description' => 'Split copy block.',
				'group'       => 'content',
				'icon'        => 'eicon-columns',
				'type'        => 'generic',
			),
			'stat-inline' => array(
				'title'       => 'Inline Stat',
				'description' => 'Number inside a sentence.',
				'group'       => 'content',
				'icon'        => 'eicon-counter',
				'type'        => 'stat_card',
			),
			'caption-card' => array(
				'title'       => 'Caption Card',
				'description' => 'Image with caption card.',
				'group'       => 'media',
				'icon'        => 'eicon-image-box',
				'type'        => 'image_caption',
			),
			'portrait' => array(
				'title'       => 'Portrait',
				'description' => 'Person photo with name.',
				'group'       => 'media',
				'icon'        => 'eicon-person',
				'type'        => 'team',
			),
			'cover-image' => array(
				'title'       => 'Cover Image',
				'description' => 'Full-bleed image with title.',
				'group'       => 'media',
				'icon'        => 'eicon-image',
				'type'        => 'overlay_card',
			),
			'logo-row' => array(
				'title'       => 'Logo Row',
				'description' => 'Single row of logos.',
				'group'       => 'media',
				'icon'        => 'eicon-logo',
				'type'        => 'logo_grid',
			),
			'youtube-card' => array(
				'title'       => 'YouTube Card',
				'description' => 'Video thumbnail card.',
				'group'       => 'media',
				'icon'        => 'eicon-youtube',
				'type'        => 'video_popup',
			),
			'vimeo-card' => array(
				'title'       => 'Vimeo Card',
				'description' => 'Vimeo link card.',
				'group'       => 'media',
				'icon'        => 'eicon-vimeo',
				'type'        => 'video_popup',
			),
			'audio-card' => array(
				'title'       => 'Audio Card',
				'description' => 'Audio player card.',
				'group'       => 'media',
				'icon'        => 'eicon-headphones',
				'type'        => 'audio',
			),
			'file-card' => array(
				'title'       => 'File Card',
				'description' => 'Downloadable file card.',
				'group'       => 'media',
				'icon'        => 'eicon-document-file',
				'type'        => 'pdf',
			),
			'gallery-masonry' => array(
				'title'       => 'Gallery Masonry',
				'description' => 'Uneven image grid.',
				'group'       => 'media',
				'icon'        => 'eicon-gallery-masonry',
				'type'        => 'image_grid',
			),
			'banner-slim' => array(
				'title'       => 'Slim Banner',
				'description' => 'Thin promo strip.',
				'group'       => 'marketing',
				'icon'        => 'eicon-banner',
				'type'        => 'notice',
			),
			'sale-pill' => array(
				'title'       => 'Sale Pill',
				'description' => 'Sale label.',
				'group'       => 'marketing',
				'icon'        => 'eicon-price-tag',
				'type'        => 'badge',
			),
			'urgency-bar' => array(
				'title'       => 'Urgency Bar',
				'description' => 'Limited-time note.',
				'group'       => 'marketing',
				'icon'        => 'eicon-countdown',
				'type'        => 'notice',
			),
			'guarantee-box' => array(
				'title'       => 'Guarantee Box',
				'description' => 'Money-back or promise note.',
				'group'       => 'marketing',
				'icon'        => 'eicon-check-circle',
				'type'        => 'icon_box',
			),
			'trial-cta' => array(
				'title'       => 'Trial CTA',
				'description' => 'Start trial block.',
				'group'       => 'marketing',
				'icon'        => 'eicon-button',
				'type'        => 'promo',
			),
			'book-cta' => array(
				'title'       => 'Book CTA',
				'description' => 'Booking call to action.',
				'group'       => 'marketing',
				'icon'        => 'eicon-calendar',
				'type'        => 'promo',
			),
			'plan-mini' => array(
				'title'       => 'Mini Plan',
				'description' => 'Compact price card.',
				'group'       => 'marketing',
				'icon'        => 'eicon-price-table',
				'type'        => 'offer',
			),
			'feature-compare' => array(
				'title'       => 'Feature Compare',
				'description' => 'Two-column feature check.',
				'group'       => 'marketing',
				'icon'        => 'eicon-table',
				'type'        => 'compare',
			),
			'social-proof-bar' => array(
				'title'       => 'Proof Bar',
				'description' => 'Short proof line.',
				'group'       => 'proof',
				'icon'        => 'eicon-review',
				'type'        => 'rating_badge',
			),
			'quote-slider' => array(
				'title'       => 'Quote Slider',
				'description' => 'Simple quote rotator.',
				'group'       => 'proof',
				'icon'        => 'eicon-testimonial-carousel',
				'type'        => 't_slider',
			),
			'avatar-row' => array(
				'title'       => 'Avatar Row',
				'description' => 'Stacked client faces.',
				'group'       => 'proof',
				'icon'        => 'eicon-person',
				'type'        => 'team_grid',
			),
			'award-badge' => array(
				'title'       => 'Award Badge',
				'description' => 'Award label.',
				'group'       => 'proof',
				'icon'        => 'eicon-trophy',
				'type'        => 'badge',
			),
			'metric-trio' => array(
				'title'       => 'Metric Trio',
				'description' => 'Three result numbers.',
				'group'       => 'data',
				'icon'        => 'eicon-counter',
				'type'        => 'skills',
			),
			'goal-bar' => array(
				'title'       => 'Goal Bar',
				'description' => 'Progress toward a goal.',
				'group'       => 'data',
				'icon'        => 'eicon-skill-bar',
				'type'        => 'progress',
			),
			'score-ring' => array(
				'title'       => 'Score Ring',
				'description' => 'Score in a ring.',
				'group'       => 'data',
				'icon'        => 'eicon-counter-circle',
				'type'        => 'circle',
			),
			'kpi-card' => array(
				'title'       => 'KPI Card',
				'description' => 'Single KPI.',
				'group'       => 'data',
				'icon'        => 'eicon-counter',
				'type'        => 'stat_card',
			),
			'mini-table' => array(
				'title'       => 'Mini Table',
				'description' => 'Small data table.',
				'group'       => 'data',
				'icon'        => 'eicon-table',
				'type'        => 'table',
			),
			'related-posts' => array(
				'title'       => 'Related Posts',
				'description' => 'Recent posts list.',
				'group'       => 'theme',
				'icon'        => 'eicon-post-list',
				'type'        => 'posts_list',
			),
			'recent-posts' => array(
				'title'       => 'Recent Posts',
				'description' => 'Latest posts grid.',
				'group'       => 'theme',
				'icon'        => 'eicon-posts-grid',
				'type'        => 'posts_grid',
			),
			'category-pills' => array(
				'title'       => 'Category Pills',
				'description' => 'Category links.',
				'group'       => 'theme',
				'icon'        => 'eicon-tags',
				'type'        => 'cats',
			),
			'search-box' => array(
				'title'       => 'Search Box',
				'description' => 'Site search.',
				'group'       => 'theme',
				'icon'        => 'eicon-search',
				'type'        => 'search',
			),
			'menu-inline' => array(
				'title'       => 'Inline Menu',
				'description' => 'Horizontal menu.',
				'group'       => 'theme',
				'icon'        => 'eicon-nav-menu',
				'type'        => 'menu',
			),
			'footer-note' => array(
				'title'       => 'Footer Note',
				'description' => 'Small legal line.',
				'group'       => 'theme',
				'icon'        => 'eicon-text',
				'type'        => 'generic',
			),
			'hours-card' => array(
				'title'       => 'Hours Card',
				'description' => 'Opening hours card.',
				'group'       => 'business',
				'icon'        => 'eicon-clock-o',
				'type'        => 'hours',
			),
			'email-button' => array(
				'title'       => 'Email Button',
				'description' => 'Mailto button.',
				'group'       => 'business',
				'icon'        => 'eicon-mail',
				'type'        => 'creative_button',
			),
			'map-card' => array(
				'title'       => 'Map Card',
				'description' => 'Address plus map.',
				'group'       => 'business',
				'icon'        => 'eicon-google-maps',
				'type'        => 'map',
			),
			'chat-button' => array(
				'title'       => 'Chat Button',
				'description' => 'Chat link button.',
				'group'       => 'business',
				'icon'        => 'eicon-comments',
				'type'        => 'whatsapp',
			),
			'location-list' => array(
				'title'       => 'Location List',
				'description' => 'Office locations.',
				'group'       => 'business',
				'icon'        => 'eicon-map-pin',
				'type'        => 'feature_list',
			),
			'form-note' => array(
				'title'       => 'Form Note',
				'description' => 'Shortcode form slot.',
				'group'       => 'forms',
				'icon'        => 'eicon-form-horizontal',
				'type'        => 'shortcode',
			),
			'embed-frame' => array(
				'title'       => 'Embed Frame',
				'description' => 'HTML embed frame.',
				'group'       => 'forms',
				'icon'        => 'eicon-code',
				'type'        => 'html_embed',
			),
			'code-snippet' => array(
				'title'       => 'Code Snippet',
				'description' => 'Escaped snippet.',
				'group'       => 'forms',
				'icon'        => 'eicon-code',
				'type'        => 'code',
			),
			'login-note' => array(
				'title'       => 'Login Note',
				'description' => 'Login form block.',
				'group'       => 'forms',
				'icon'        => 'eicon-lock-user',
				'type'        => 'login',
			),
			'product-row' => array(
				'title'       => 'Product Row',
				'description' => 'Woo product row.',
				'group'       => 'woo',
				'icon'        => 'eicon-products',
				'type'        => 'woo_products',
			),
			'category-row' => array(
				'title'       => 'Category Row',
				'description' => 'Woo category row.',
				'group'       => 'woo',
				'icon'        => 'eicon-product-categories',
				'type'        => 'woo_cats',
			),
			'cart-note' => array(
				'title'       => 'Cart Note',
				'description' => 'Sale or cart note.',
				'group'       => 'woo',
				'icon'        => 'eicon-cart',
				'type'        => 'woo_sale',
			),
			'ticker-lite' => array(
				'title'       => 'Ticker Lite',
				'description' => 'Short news ticker.',
				'group'       => 'utility',
				'icon'        => 'eicon-post-list',
				'type'        => 'ticker',
			),
			'scroll-text' => array(
				'title'       => 'Scroll Text',
				'description' => 'Marquee sentence.',
				'group'       => 'utility',
				'icon'        => 'eicon-animation-text',
				'type'        => 'marquee',
			),
			'share-row' => array(
				'title'       => 'Share Row',
				'description' => 'Share links.',
				'group'       => 'utility',
				'icon'        => 'eicon-share',
				'type'        => 'share',
			),
			'social-row' => array(
				'title'       => 'Social Row',
				'description' => 'Profile links.',
				'group'       => 'utility',
				'icon'        => 'eicon-social-icons',
				'type'        => 'social',
			),
			'top-link' => array(
				'title'       => 'Top Link',
				'description' => 'Back to top link.',
				'group'       => 'utility',
				'icon'        => 'eicon-arrow-up',
				'type'        => 'top',
			),
			'login-gate' => array(
				'title'       => 'Login Gate',
				'description' => 'Logged-in only note.',
				'group'       => 'utility',
				'icon'        => 'eicon-lock-user',
				'type'        => 'protected',
			),
			'event-card' => array(
				'title'       => 'Event Card',
				'description' => 'Date card.',
				'group'       => 'utility',
				'icon'        => 'eicon-calendar',
				'type'        => 'event',
			),
			'clock-card' => array(
				'title'       => 'Clock Card',
				'description' => 'Timezone clock.',
				'group'       => 'utility',
				'icon'        => 'eicon-clock-o',
				'type'        => 'clock',
			),
			'tag-row' => array(
				'title'       => 'Tag Row',
				'description' => 'Tag cloud.',
				'group'       => 'utility',
				'icon'        => 'eicon-tags',
				'type'        => 'tags',
			),
			'page-list' => array(
				'title'       => 'Page List',
				'description' => 'Page sitemap.',
				'group'       => 'utility',
				'icon'        => 'eicon-sitemap',
				'type'        => 'sitemap',
			),
			'motion-label' => array(
				'title'       => 'Motion Label',
				'description' => 'Animated label.',
				'group'       => 'utility',
				'icon'        => 'eicon-animation',
				'type'        => 'motion',
			),
		);
	}

	public static function get( $id ) {
		$all = self::all();
		return isset( $all[ $id ] ) ? $all[ $id ] : null;
	}
}

